// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfGib1UQyYd8EuRNGBZz6-_wdF3vu6eus',
    appId: '1:740023908340:web:755a948673bad41f1aeba1',
    messagingSenderId: '740023908340',
    projectId: 'trustmebro-9f8d4',
    authDomain: 'trustmebro-9f8d4.firebaseapp.com',
    storageBucket: 'trustmebro-9f8d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKPLw5imyaZxPjVKpVO8BnoDgWYnHG9w',
    appId: '1:740023908340:android:23b080f30b1eec3b1aeba1',
    messagingSenderId: '740023908340',
    projectId: 'trustmebro-9f8d4',
    storageBucket: 'trustmebro-9f8d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1vEJ1o5vKJAG-No9gsqGaWOONHJ5ztXc',
    appId: '1:740023908340:ios:0f13a9f0505c4f351aeba1',
    messagingSenderId: '740023908340',
    projectId: 'trustmebro-9f8d4',
    storageBucket: 'trustmebro-9f8d4.appspot.com',
    iosBundleId: 'com.example.projectTrustmebro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1vEJ1o5vKJAG-No9gsqGaWOONHJ5ztXc',
    appId: '1:740023908340:ios:ebdaf0abd300f1cf1aeba1',
    messagingSenderId: '740023908340',
    projectId: 'trustmebro-9f8d4',
    storageBucket: 'trustmebro-9f8d4.appspot.com',
    iosBundleId: 'com.example.projectTrustmebro.RunnerTests',
  );
}
